spellchecker: aspell

matrix:
  - name: markdown
    default_encoding: utf-8
    sources:
      - "**/*.md"
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: true
          ignores:
            - code
            - pre
      - pyspelling.filters.url:
    aspell:
      lang: en
      d: en_GB
    dictionary:
      encoding: utf-8
      wordlists:
        - .aspell.en.pws
