language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - cpanminus
      - libcarp-assert-perl
      - libdate-calc-perl
      - libexperimental-perl
      - libfile-basedir-perl
      - libgetopt-long-descriptive-perl
      - libyaml-libyaml-perl
install:
  - sudo cpanm Config::Onion
  - sudo cpanm DateTime::Format::Strptime
  - pip install beancount==2.0
script:
  - make test
